server:
  port: 8000

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    multiplications:
      path: /multiplications/**
      serviceId: multiplication
      strip-prefix: false
    results:
      path: /results/**
      serviceId: multiplication
      strip-prefix: false
    leaders:
      path: /leaders/**
      serviceId: gamification
      strip-prefix: false
    stats:
      path: /stats/**
      serviceId: gamification
      strip-prefix: false

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false

eureka:
  client:
    service-url:
      #default-zone: http://localhost:8761/
      #default-zone: http://192.168.163.128:8761/
      default-zone: http://172.18.0.2:8761/